config/routes.rb
Rails.application.routes.draw do
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
# models/article.rb
class Article < ApplicationRecord
  validates_presence_of :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
#app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/index.html.erb
<h1> All Articles </h1>

<ul id='articles'>
  <% @articles.each do |article| %>
    <li>
      <%= link_to article.title, article_path(article), class: 'article-title', id: "article-#{article.id}" %>
    </li>
  <% end %>
</ul>

<%= link_to 'Create a New Article', new_article_path, class: 'new-article' %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<p><%= @article.body %></p>
<%= link_to "<< Back to Articles List", articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blogger</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>